version: '3.9'
services:
  postgres:
    image: postgres:13.2
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    container_name: postgres-db

volumes:
  postgres_data:
