version: '3.9'
services:
  backend:
    build:
      context: .
      # target: dev
    container_name: sefaz-api-notification
    volumes:
      - .:/home/node/app
      - backend_node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - APP_PORT=3000
      - APP_SECRET=DUAIUSDHAUIWD
    entrypoint: npm run start:dev

volumes:
  postgres_data:
  backend_node_modules:
